name: ipcc_ar6

channels:
    - conda-forge

dependencies:
  - python=3.7
  - affine=2.3
  - black
  - bottleneck=1.3
  - cartopy=0.18
  - cdo=1.9.8
  - cf_units=2.0
  - cftime=1.3
  - cmocean=2.0
  - dask=2.30
  - descartes=1.1
  - docopt=0.6
  - ecmwf_grib=1.14
  - flake8
  - geopandas=0.8
  - gridfill=1.0
  - h5netcdf=0.8
  - ipython
  - isort
  - jupyter_contrib_nbextensions
  - jupyter
  - line_profiler
  - matplotlib=3.3
  - nb_black
  - nc-time-axis=1.2
  - netcdf4=1.5.4
  - numba=1.19
  - numpy=1.19
  - openpyxl
  - pandas=1.2
  - parse=1.18
  - patsy=0.5
  - pint=0.16
  - pip
  - pooch=1.3
  - pytest
  - pytest-cov
  - python-cdo=1.5
  - pyyaml=5.3
  - rasterio=1.1
  - regionmask=0.6
  - scikit-learn=0.23
  - scipy=1.5
  - seaborn=0.11
  - shapely=1.7
  - statsmodels=0.12
  - tabulate=0.8
  - windspharm=1.7
  - xarray=0.17
  - xclim=0.17
  - xesmf=0.4
  - xlwt=1.3
  - zarr=2.6
  - pip:
    - git+https://github.com/mathause/mplotutils.git
